Link retrieval update
waldo-vision/models pull request #20
Opened 2023-04-18 20:27 UTC by Joe-TheBro

Worked with DevOps to change and implement with frontend api

2023-04-22 21:32 UTC, Bensikrac commented on utils/link_retrieval.py
> +        for page in range(0, total_pages + 1):  # Query all pages sequentially
Maybe add an indicator for current page here, since script seems to appear frozen for a long time like:
`print(f"Requesting page {page}")`

2023-04-22 21:33 UTC, jaredb1011 requested changes
Seems like some WIP stuff is still in here

2023-04-22 21:33 UTC, jaredb1011 commented on utils/segmentation.py
> +# img_path = "/models/utils/Screenshot.jpg"
We should remove testing code, or dead commented out code

2023-04-22 21:33 UTC, jaredb1011 commented on utils/Screenshot.jpg
What is the purpose of this file? I'm assuming this was used for testing, but we should remove it from the PR unless we create a dedicated set of unit test and test resources down the line.

2023-04-23 20:57 UTC, jaredb1011 approved these changes

2023-04-25 05:11 UTC, evoreign approved these changes

2023-04-25 14:55 UTC, merged